-- Wheel Library raw table for Supabase/Postgres
-- Generated from Wheel_Library.csv
-- Rows in uploaded file: 151,483
-- Columns in uploaded file: 121
-- Strategy: keep all source columns as text first to avoid data loss/import errors.

CREATE TABLE IF NOT EXISTS public.wheel_library_raw (
    db_row_id bigserial PRIMARY KEY,
    upload_batch_id uuid NOT NULL,
    uploaded_at timestamptz NOT NULL DEFAULT now(),
    "data_part_no" text,
    "vendor_part_no" text,
    "mpn" text,
    "sku" text,
    "dww_part_no" text,
    "global_part_no" text,
    "vendor_description" text,
    "brand" text,
    "model" text,
    "style" text,
    "style_name" text,
    "size" text,
    "wheel_diameter" text,
    "wheel_width" text,
    "bolt_pattern1" text,
    "bolt_pattern2" text,
    "bolt_pattern" text,
    "lug_holes" text,
    "offset1" text,
    "simpleoffset" text,
    "hub" text,
    "finish" text,
    "basic_finish" text,
    "lip_finish" text,
    "vendor_code" text,
    "manufacturer_finish" text,
    "manufacturer_finish_code" text,
    "load_rating" text,
    "back_spacing" text,
    "lip_depth" text,
    "countryof_origin" text,
    "upccode" text,
    "cap" text,
    "cappart_no" text,
    "warranty" text,
    "image" text,
    "side_image" text,
    "additional_images" text,
    "wheel_vizualizer_image" text,
    "weight" text,
    "length" text,
    "width" text,
    "height" text,
    "dim_weight" text,
    "girth" text,
    "weight_for_shipping" text,
    "bandable" text,
    "xfactor" text,
    "discontinued" text,
    "wheel_construction" text,
    "offroad" text,
    "dually" text,
    "staggered" text,
    "wheel_style" text,
    "vehicle_type_car" text,
    "vehicle_type_suv" text,
    "vehicle_type_truck" text,
    "vehicle_type_offroad" text,
    "vehicle_type_trailer" text,
    "vehicle_type_atv_utv" text,
    "url_key" text,
    "invoice_price" text,
    "map_col" text,
    "msrp" text,
    "rebates" text,
    "net_price" text,
    "markup" text,
    "costof_shipping" text,
    "average_single" text,
    "average_double" text,
    "oversized_shipping_cost" text,
    "peak_season_shipping_cost" text,
    "retail_price" text,
    "website_display_price" text,
    "retailprice_before_mapcap" text,
    "mapcapprice" text,
    "fakeprice" text,
    "fakepercent" text,
    "cost_without_markup" text,
    "lowest_competitor_price" text,
    "lowest_competitor_name" text,
    "we_have_advantage_on_the_pricing" text,
    "all_qty" text,
    "location_qty" text,
    "last_date_all_qty" text,
    "all_local_qty" text,
    "last_date_local_qty" text,
    "instock_flag" text,
    "local_vendor" text,
    "local_instock" text,
    "rebate_on_consumer" text,
    "rebate_amount" text,
    "rebate_url" text,
    "rebate_product_image" text,
    "preferred_product" text,
    "local_flag_for_website" text,
    "flag_for_website" text,
    "customizable" text,
    "sale_type" text,
    "date_added" text,
    "rawimage" text,
    "wheel_type" text,
    "wheel_type_description" text,
    "model_url" text,
    "model_url_selected" text,
    "acima_loggedin_price" text,
    "acima_loggedin_pricex4" text,
    "acima_notloggedin_price" text,
    "acima_notloggedin_pricex4" text,
    "affirm_loggedin_price" text,
    "affirm_loggedin_pricex4" text,
    "affirm_notloggedin_price" text,
    "affirm_notloggedin_pricex4" text,
    "image_url" text,
    "additional_image_url" text,
    "entity_id" text,
    "front_image" text,
    "combined_attribute" text,
    "promo_amount" text,
    "custom_promo_id" text,
    "id_col" text,
    sku_clean text GENERATED ALWAYS AS (upper(trim("sku"))) STORED
);

CREATE INDEX IF NOT EXISTS idx_wheel_library_raw_sku ON public.wheel_library_raw ("sku");
CREATE INDEX IF NOT EXISTS idx_wheel_library_raw_brand ON public.wheel_library_raw ("brand");
CREATE INDEX IF NOT EXISTS idx_wheel_library_raw_model ON public.wheel_library_raw ("model");
CREATE INDEX IF NOT EXISTS idx_wheel_library_raw_vendor_part_no ON public.wheel_library_raw ("vendor_part_no");
CREATE INDEX IF NOT EXISTS idx_wheel_library_raw_mpn ON public.wheel_library_raw ("mpn");
CREATE INDEX IF NOT EXISTS idx_wheel_library_raw_wheel_diameter ON public.wheel_library_raw ("wheel_diameter");
CREATE INDEX IF NOT EXISTS idx_wheel_library_raw_wheel_width ON public.wheel_library_raw ("wheel_width");
CREATE INDEX IF NOT EXISTS idx_wheel_library_raw_bolt_pattern ON public.wheel_library_raw ("bolt_pattern");
CREATE INDEX IF NOT EXISTS idx_wheel_library_raw_vendor_code ON public.wheel_library_raw ("vendor_code");
CREATE INDEX IF NOT EXISTS idx_wheel_library_raw_sku_clean ON public.wheel_library_raw ((upper(trim("sku"))));
CREATE INDEX IF NOT EXISTS idx_wheel_library_raw_brand_sku ON public.wheel_library_raw ("brand", "sku");

-- Useful quality checks after upload:
-- SELECT count(*) AS total_rows FROM public.wheel_library_raw;
-- SELECT count(*) AS rows_with_sku FROM public.wheel_library_raw WHERE sku_clean <> '';
-- SELECT sku_clean, count(*) FROM public.wheel_library_raw GROUP BY sku_clean HAVING count(*) > 1 ORDER BY count(*) DESC LIMIT 50;
-- SELECT brand, count(*) FROM public.wheel_library_raw GROUP BY brand ORDER BY count(*) DESC LIMIT 50;
